Description: OAP XML Integration Services Resources - ${self:provider.regionCode} ${self:provider.stage}
Resources:
  OAPResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}
  OAPResourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: ${self:service}-${self:provider.stage}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Allows3GetObject-${self:provider.stage}'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${self:service}-EventBridgeEventHandler-${self:provider.stage}'
            Action: 's3:GetObject'
            Resource: arn:aws:s3:::${self:service}-${self:provider.stage}/*
Outputs:
  OAPResourceBucket:
    Description: 'CA OAP Resources Bucket'
    Value: !Ref OAPResourceBucket
    Export:
      Name: OAPResourceBucket
  OAPResourceBucketArn:
    Description: 'CA OAP Resources Arn'
    Value: !GetAtt OAPResourceBucket.Arn
    Export:
      Name: OAPResourceBucketArn
